# Generated by Django 5.2.3 on 2025-06-13 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fralda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convidado', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Presente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(null=True, upload_to='presentes/')),
                ('link', models.CharField(max_length=350)),
                ('quantidade', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fralda_Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.convidado')),
                ('id_fralda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fralda')),
            ],
        ),
        migrations.CreateModel(
            name='Presente_Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.convidado')),
                ('id_presente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.presente')),
            ],
        ),
        migrations.AddField(
            model_name='fralda',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tamanho'),
        ),
    ]
